In [1]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/Premalatha-success/Datasets/refs/heads/main/AutoInsurance.csv')
df.head()

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,3/2/2011,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize

In [2]:
df=df.drop(["Customer","Effective To Date"],axis=1)

In [3]:
from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_cols = df.select_dtypes(include='object').columns

# Apply Label Encoding
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

print("DataFrame after Label Encoding:")
print(df.head())

DataFrame after Label Encoding:
   State  Customer Lifetime Value  Response  Coverage  Education  \
0      4              2763.519279         0         0          0
1      0              6979.535903         0         1          0
2      2             12887.431650         0         2          0
3      1              7645.861827         0         0          0
4      4              2813.692575         0         0          0

   EmploymentStatus  Gender  Income  Location Code  Marital Status  ...  \
0                 1       0   56274              1               1  ...
1                 4       0       0              1               2  ...
2                 1       0   48767              1               1  ...
3                 4       1       0              1               1  ...
4                 1       1   43836              0               2  ...

   Months Since Policy Inception  Number of Open Complaints  \
0                              5                          0
1                             42                          0
2                             38                          0
3                             65                          0
4                             44                          0

   Number of Policies  Policy Type  Policy  Renew Offer Type  Sales Channel  \
0                   1            0       2                 0              0
1                   8            1       5                 2              0
2                   2            1       5                 0              0
3                   7            0       1                 0              2
4                   1            1       3                 0              0

   Total Claim Amount  Vehicle Class  Vehicle Size
0          384.811147              5             1
1         1131.464935              0             1
2          566.472247              5             1
3          529.881344              3             1
4          138.130879              0             1

[5 rows x 22 columns]

In [4]:
df.isnull().sum()

State                            0
Customer Lifetime Value          0
Response                         0
Coverage                         0
Education                        0
EmploymentStatus                 0
Gender                           0
Income                           0
Location Code                    0
Marital Status                   0
Monthly Premium Auto             0
Months Since Last Claim          0
Months Since Policy Inception    0
Number of Open Complaints        0
Number of Policies               0
Policy Type                      0
Policy                           0
Renew Offer Type                 0
Sales Channel                    0
Total Claim Amount               0
Vehicle Class                    0
Vehicle Size                     0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9134 entries, 0 to 9133
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   State                          9134 non-null   int64
 1   Customer Lifetime Value        9134 non-null   float64
 2   Response                       9134 non-null   int64
 3   Coverage                       9134 non-null   int64
 4   Education                      9134 non-null   int64
 5   EmploymentStatus               9134 non-null   int64
 6   Gender                         9134 non-null   int64
 7   Income                         9134 non-null   int64
 8   Location Code                  9134 non-null   int64
 9   Marital Status                 9134 non-null   int64
 10  Monthly Premium Auto           9134 non-null   int64
 11  Months Since Last Claim        9134 non-null   int64
 12  Months Since Policy Inception  9134 non-null   int64
 13  Number of Open Complaints      9134 non-null   int64
 14  Number of Policies             9134 non-null   int64
 15  Policy Type                    9134 non-null   int64
 16  Policy                         9134 non-null   int64
 17  Renew Offer Type               9134 non-null   int64
 18  Sales Channel                  9134 non-null   int64
 19  Total Claim Amount             9134 non-null   float64
 20  Vehicle Class                  9134 non-null   int64
 21  Vehicle Size                   9134 non-null   int64
dtypes: float64(2), int64(20)
memory usage: 1.5 MB

In [6]:
Y=df[["Customer Lifetime Value"]]
X=df.drop(["Customer Lifetime Value"],axis=1)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [9]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [10]:
model.score(X_train,Y_train)

0.17196784589278535

In [11]:
model.score(X_test,Y_test)

0.1281506458579792

In [14]:
from sklearn.tree import DecisionTreeRegressor
model_dt=DecisionTreeRegressor(max_depth=9)
model_dt.fit(X_train,Y_train)
print(model_dt.score(X_train,Y_train))
print(model_dt.score(X_test,Y_test))

0.7998217859830367
0.5834971448179147

In [ ]:
### Remove the outliers without loss of data using IQR

In [15]:
numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)

print("DataFrame after outlier treatment:")
print(df.head())

DataFrame after outlier treatment:
   State  Customer Lifetime Value  Response  Coverage  Education  \
0      4              2763.519279         0         0          0
1      0              6979.535903         0         1          0
2      2             12887.431650         0         2          0
3      1              7645.861827         0         0          0
4      4              2813.692575         0         0          0

   EmploymentStatus  Gender  Income  Location Code  Marital Status  ...  \
0                 1       0   56274              1               1  ...
1                 4       0       0              1               2  ...
2                 1       0   48767              1               1  ...
3                 4       1       0              1               1  ...
4                 1       1   43836              1               2  ...

   Months Since Policy Inception  Number of Open Complaints  \
0                              5                          0
1                             42                          0
2                             38                          0
3                             65                          0
4                             44                          0

   Number of Policies  Policy Type  Policy  Renew Offer Type  Sales Channel  \
0                 1.0            1       2                 0              0
1                 8.0            1       5                 2              0
2                 2.0            1       5                 0              0
3                 7.0            1       1                 0              2
4                 1.0            1       3                 0              0

   Total Claim Amount  Vehicle Class  Vehicle Size
0          384.811147              5             1
1          960.399730              0             1
2          566.472247              5             1
3          529.881344              3             1
4          138.130879              0             1

[5 rows x 22 columns]

In [16]:
Y=df[["Customer Lifetime Value"]]
X=df.drop(["Customer Lifetime Value"],axis=1)

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [18]:
from sklearn.tree import DecisionTreeRegressor
model_dt=DecisionTreeRegressor(max_depth=7)
model_dt.fit(X_train,Y_train)
print(model_dt.score(X_train,Y_train))
print(model_dt.score(X_test,Y_test))

0.8858562141604822
0.8650249235562002

In [ ]:
from sklearn.ensemble import RandomForestRegressor
### score ->

In [19]:
from sklearn.ensemble import GradientBoostingRegressor
model_gbr=GradientBoostingRegressor(max_depth=5,n_estimators=100)
model_gbr.fit(X_train,Y_train)
print(model_gbr.score(X_train,Y_train))
print(model_gbr.score(X_test,Y_test))

/usr/local/lib/python3.12/dist-packages/sklearn/ensemble/_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

0.9147121077139673
0.878179305346995

In [ ]:
### Instead of outlier we can also go ahead with log transformation